"""Add clerk_user_id, email, username to users table

Revision ID: 56ef1ee4b63b
Revises: 2f406a3942f1
Create Date: 2025-09-14 01:14:38.429641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ef1ee4b63b'
down_revision: Union[str, Sequence[str], None] = '2f406a3942f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_user_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.alter_column('users', 'callsign',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.alter_column('users', 'callsign',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'username')
    op.drop_column('users', 'email')
    op.drop_column('users', 'clerk_user_id')
    # ### end Alembic commands ###
