"""Add callsign_change_requests table

Revision ID: 7eb963fc3a44
Revises: 003_linked_callsigns
Create Date: 2026-06-10 21:42:20.036427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb963fc3a44'
down_revision: Union[str, Sequence[str], None] = '003_linked_callsigns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callsign_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_callsign', sa.String(), nullable=True),
    sa.Column('new_callsign', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callsign_change_requests_id'), 'callsign_change_requests', ['id'], unique=False)
    op.create_index(op.f('ix_callsign_change_requests_user_id'), 'callsign_change_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_callsign_change_requests_user_id'), table_name='callsign_change_requests')
    op.drop_index(op.f('ix_callsign_change_requests_id'), table_name='callsign_change_requests')
    op.drop_table('callsign_change_requests')
    # ### end Alembic commands ###
