"""Create qso_logs table

Revision ID: 9b241c567b38
Revises: 
Create Date: 2025-08-13 22:56:39.089288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b241c567b38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qso_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('freq', sa.Float(), nullable=True),
    sa.Column('spotter', sa.String(), nullable=True),
    sa.Column('dx', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotter', 'area', name='unique_spotter_area')
    )
    op.create_index(op.f('ix_qso_logs_area'), 'qso_logs', ['area'], unique=False)
    op.create_index(op.f('ix_qso_logs_dx'), 'qso_logs', ['dx'], unique=False)
    op.create_index(op.f('ix_qso_logs_id'), 'qso_logs', ['id'], unique=False)
    op.create_index(op.f('ix_qso_logs_spotter'), 'qso_logs', ['spotter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qso_logs_spotter'), table_name='qso_logs')
    op.drop_index(op.f('ix_qso_logs_id'), table_name='qso_logs')
    op.drop_index(op.f('ix_qso_logs_dx'), table_name='qso_logs')
    op.drop_index(op.f('ix_qso_logs_area'), table_name='qso_logs')
    op.drop_table('qso_logs')
    # ### end Alembic commands ###
