"""Add region field to users table

Revision ID: 9be008a716cd
Revises: 56ef1ee4b63b
Create Date: 2025-09-16 01:58:32.277885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be008a716cd'
down_revision: Union[str, Sequence[str], None] = '56ef1ee4b63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'region')
    # ### end Alembic commands ###
